language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements/test.txt
  - pip install -r requirements/requirements.txt
  - pip install -q Django$DJANGO_VERSION
script:
  - coverage run --source=pseudo_cms manage.py test
  - coverage report --show-missing
  - flake8 pseudo_cms --exclude=pseudo_cms/south_migrations/*,pseudo_cms/migrations* --max-line-length=120

env:
  - DJANGO_VERSION=">=1.10,<1.11"
  - DJANGO_VERSION=">=1.11,<1.12"
  - DJANGO_VERSION=">=2.0,<2.1"
  - DJANGO_VERSION=">=2.1,<2.2"
