dist: xenial
language: python

matrix:
    fast_finish: true
    include:
      - { python: "3.6", env: DJANGO_VERSION=1.11 }
      - { python: "3.6", env: DJANGO_VERSION=2.0 }
      - { python: "3.6", env: DJANGO_VERSION=2.1 }
      - { python: "3.6", env: DJANGO_VERSION=2.2 }
      - { python: "3.6", env: DJANGO_VERSION=3.0 }
      - { python: "3.6", env: DJANGO_VERSION=3.1 }

      - { python: "3.7", env: DJANGO_VERSION=2.0 }
      - { python: "3.7", env: DJANGO_VERSION=2.1 }
      - { python: "3.7", env: DJANGO_VERSION=2.2 }
      - { python: "3.7", env: DJANGO_VERSION=3.0 }
      - { python: "3.7", env: DJANGO_VERSION=3.1 }

      - { python: "3.8", env: DJANGO_VERSION=2.2 }
      - { python: "3.8", env: DJANGO_VERSION=3.0 }
      - { python: "3.8", env: DJANGO_VERSION=3.1 }

install:
  - pip install -r requirements/test.txt
  - pip install -r requirements/requirements.txt
  - pip install -q Django==$DJANGO_VERSION
script:
  - coverage run --source=pseudo_cms manage.py test
  - coverage report --show-missing
  - flake8 pseudo_cms --exclude=pseudo_cms/south_migrations/*,pseudo_cms/migrations* --max-line-length=120
