language: python

matrix:
    fast_finish: true
    include:
      - { python: "2.7", env: DJANGO_VERSION=1.10 }
      - { python: "2.7", env: DJANGO_VERSION=1.11 }
      - { python: "2.7", env: DJANGO_VERSION=2.0 }

      - { python: "3.5", env: DJANGO_VERSION=1.10 }
      - { python: "3.5", env: DJANGO_VERSION=1.11 }
      - { python: "3.5", env: DJANGO_VERSION=2.0 }

      - { python: "3.6", env: DJANGO_VERSION=1.10 }
      - { python: "3.6", env: DJANGO_VERSION=1.11 }
      - { python: "3.6", env: DJANGO_VERSION=2.0 }

      - { python: "3.7-dev", env: DJANGO_VERSION=2.0 }

install:
  - pip install -r requirements/test.txt
  - pip install -r requirements/requirements.txt
  - pip install -q Django$DJANGO_VERSION
script:
  - coverage run --source=pseudo_cms manage.py test
  - coverage report --show-missing
  - flake8 pseudo_cms --exclude=pseudo_cms/south_migrations/*,pseudo_cms/migrations* --max-line-length=120
