language: python
python:
  - "2.7"
install:
  - pip install -r requirements/test.txt
  - pip install -r requirements/requirements.txt
  - pip install -q Django$DJANGO_VERSION
script:
  - coverage run --source=pseudo_cms manage.py test
  - coverage report --show-missing
  - flake8 blogger --exclude=pseudo_cms/south_migrations/*,pseudo_cms/migrations* --max-line-length=120

env:
  - DJANGO_VERSION=">=1.8,<1.9"
  - DJANGO_VERSION=">=1.9,<1.10"
  - DJANGO_VERSION=">=1.10,<1.11"
  - DJANGO_VERSION=">=1.11,<1.12"
